//*********************************************************************
//xCAD
//Copyright(C) 2023 Xarial Pty Limited
//Product URL: https://www.xcad.net
//License: https://xcad.xarial.com/license/
//*********************************************************************

using Xarial.XCad.Geometry;

namespace Xarial.XCad.Features.CustomFeature.Structures
{
    /// <summary>
    /// Rebuild result of the <see cref="IXCustomFeature"/>
    /// </summary>
    public class CustomFeatureRebuildResult
    {
        /// <summary>
        /// Status result
        /// </summary>
        public bool Result { get; set; }

        /// <summary>
        /// Error message
        /// </summary>
        public string ErrorMessage { get; set; }
    }

    /// <summary>
    /// Bodies result of the <see cref="IXCustomFeature"/>
    /// </summary>
    public class CustomFeatureBodyRebuildResult : CustomFeatureRebuildResult
    {
        /// <summary>
        /// Bodies generated by macro feature
        /// </summary>
        public IXBody[] Bodies { get; set; }
    }
}