<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Xarial.XCad.Toolkit.Windows</AssemblyName>
    <RootNamespace>Xarial.XCad.Toolkit.Windows</RootNamespace>
    <TargetFrameworks>net9.0-windows;net8.0-windows;net7.0-windows;net6.0-windows;netcoreapp3.1;net461</TargetFrameworks>
    <PackageId>Xarial.XCad.Toolkit.Windows</PackageId>
    <PackageTags>cad,solidworks</PackageTags>
    <Description>Utility classes for implementing xCAD.NET - Framework for developing CAD applications for Windows platforms</Description>
    <PackageIcon>icon.png</PackageIcon>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
    <PackageIconUrl>https://xcad.xarial.com/icon-toolkit.png</PackageIconUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <Import Project="..\..\common\common.props" />

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DocumentationFile>Xarial.XCad.Toolkit.Windows.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="icon.png" pack="true" PackagePath="" Link="_Pack\icon.png" />
    <None Include="..\..\LICENSE.md" pack="true" PackagePath="" Link="_Pack\LICENSE.md" />
    <None Include="..\..\README.md" pack="true" PackagePath="" Link="_Pack\README.md" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="_Pack\" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Base\Base.csproj" />
    <ProjectReference Include="..\Toolkit\Toolkit.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.1.1" PrivateAssets="All" />
  </ItemGroup>
  
</Project>